on:
  schedule:
    - cron:  '10 4 * * *'
name: Pull Data Daily
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Pull
      run: node cli.js daily-action
      env:
        GHTOKEN: ${{ secrets.GHTOKEN }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
