on:
  schedule:
    - cron:  '40 4 1 * *'
name: Update Owner Index
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Pull
      run: node cli.js owner-index
      env:
        GHTOKEN: ${{ secrets.GHTOKEN }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
